### ISSUE TITLE
Return gridpool trades

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-electricity-trading#28]
### What's needed?

Currently there is no way to retrieve individual gridpool level trades data. The difference between trades and orders is that an order can result into multiple trades each having its own status, price and quantity. Also an order has its own initial quantity.

### Proposed solution

Introduce two new RPC endpoints:

```Protobuf
// Service providing operations related to order management.
service ElectricityTradingService {

  // ....
  
  // Lists all trades for a given Gridpool.
  rpc ListGridpoolTrades(ListGridpoolTradesRequest)
      returns (ListGridpoolTradesResponse);

  // Stream trades for a given Gridpool.
  rpc ReceiveGridpoolTradesStream(ReceiveGridpoolTradesStreamRequest)
      returns (stream ReceiveGridpoolTradesStreamResponse);

  // ....

}
```

Note on TradeState: see this related issue [here](https://github.com/frequenz-floss/frequenz-api-electricity-trading/issues/29)
```Protobuf
// Enum for the state of a trade.
enum TradeState {
   // ...
}
```

```Protobuf
// Represents a private trade in the electricity market.
// 
// !!! note
//     This represents either the buy or sell side of a trade which is different to 
//     public trade information which always represents both sides of a market.
message Trade {
  // ID of the trade.
  uint64 id = 1;

  // ID of the order.
  uint64 order_id = 2;

  // Indicates if the trades order was on the Buy or Sell side of the market.
  MarketSide side = 3;

  // Delivery area of the trade.
  frequenz.api.common.v1.grid.DeliveryArea delivery_area = 4;

  // The delivery period for the contract.
  frequenz.api.common.v1.grid.DeliveryPeriod delivery_period = 5;

  // UTC Timestamp of the trades execution time.
  google.protobuf.Timestamp execution_time = 6;

  // The price at which the trade was executed.
  frequenz.api.common.v1.market.Price price = 7;

  // The executed quantity of the trade.
  frequenz.api.common.v1.market.Energy quantity = 8;

  // Current state of the trade.
  TradeState state = 9;
}
```

```Protobuf
// Parameters for filtering Gridpool trades.
//
// !!! note
//     Multiple filters can be used in combination to narrow down the returned
//     results. For example, you can apply both state and side filters
//     simultaneously to list only the trades on the buy side of the
//     market.
message GridpoolTradeFilter {
  // Optional filter for the trade state.
  repeated TradeState states = 1;

  // Optional filter for the given order id´s.
  repeated uint64 order_id_list = 2;

  // Optional filter for the trades order side.
  optional MarketSide side = 3;

  // Optional filter for delivery period.
  frequenz.api.common.v1.grid.DeliveryPeriod delivery_period = 4;

  // Optional filter for delivery area.
  frequenz.api.common.v1.grid.DeliveryArea delivery_area = 5;
}
```

```Protobuf
// Request to retrieve a list of trades for a specific Gridpool.
message ListGridpoolTradesRequest {
  // The Gridpool to retrieve the trades for.
  uint64 gridpool_id = 1;

  // Optional Gridpool trades filter.
  GridpoolTradeFilter filter = 2;

  // Pagination parameters.
  frequenz.api.common.v1.pagination.PaginationParams pagination_params = 3;
}

// Response from listing trades for a given Gridpool.
message ListGridpoolTradesResponse {
  // List of all listed trades with their details.
  repeated Trade trades_list = 1;

  // Metadata for pagination, including token for next page to retrieve.
  frequenz.api.common.v1.pagination.PaginationInfo pagination_info = 2;
}

// Subscribe to the stream of gridpool trades.
// This method provides real-time updates on newly executed gridpool trades,
// making it useful dynamic analytics and real-time decision-making.
message ReceiveGridpoolTradesStreamRequest {
  // Optional filter to specify which trades should be included in the stream.
  TradeFilter filter = 1;
}

// Response to a subscription request for a stream of Gridpool trades.
// Real-time information on trades is pushed through this response.
message ReceiveGridpoolTradesStreamResponse {
  // The trade that has been executed and is being broadcasted in
  // real-time.
  Trade trade = 1;
}
```

**Comment by cwasicki** [comment]
> message Trade {

Maybe `PrivateTrade`

>   // ID of the trade.
  uint64 id = 1;

Is this the ID matching the one from the public order book (in public trade)?

>   // Delivery area of the trade.
  frequenz.api.common.v1.grid.DeliveryArea delivery_area = 4;

Is this the area of the gridpool, or the one where the energy is being "delivered"?

>   // UTC Timestamp of the trades execution time.
  google.protobuf.Timestamp execution_time = 6;

I wonder why private trades have only execution time and public trades only modification time. Maybe both Trade types should have both times?

> message GridpoolTradeFilter {

Could be convenient to also filter on execution time.

> message ReceiveGridpoolTradesStreamRequest {
  // Optional filter to specify which trades should be included in the stream.
  TradeFilter filter = 1;
}

Don't we need `gridpool_id` here?

**Comment by ghost** [comment]
> Could be convenient to also filter on execution time.

True, could be useful but in this case it should be implemented as bounds then because execution times are down to the milisecond.

**Comment by ghost** [comment]
> Maybe `PrivateTrade`

hmm I don't think the distinction is super necessary, but in case we wanna do this then we'd also have to change how we define `Order`. 

> Is this the ID matching the one from the public order book (in public trade)?

No I don't think so

**Comment by ghost** [comment]
> ```
> // ID of the trade.
>   uint64 id = 1;
> ```

This could maybe be `trade_id`, since the id of the orders are named `order_id`


> ```
> // Delivery area of the trade.
>   frequenz.api.common.v1.grid.DeliveryArea delivery_area = 4;
> ```

We don't get the buy and sell delivery areas here right?

**Comment by thomas-nicolai-frequenz** [comment]
> This could maybe be trade_id, since the id of the orders are named order_id

No please don't. This would introduce inconsistencies across all APIs.

**Comment by thomas-nicolai-frequenz** [comment]
> True, could be useful but in this case it should be implemented as bounds then because execution times are down to the milisecond.

If there is no immediate use case lets please postpone this.
